"""
governance/tier_b_gate.py
=========================
Tier B — Formal Release Gate (Human-in-the-Loop).

When a project is deemed ready for public/production release, execution
freezes and a structured Release Card is written to the release_gate/
directory. The Operator approves by dropping a `.AUTHORIZE` file.

File-based protocol (no UI required):
  - Freeze:   write  `release_gate/{project_id}.PENDING.md`
  - Authorize: drop   `release_gate/{project_id}.AUTHORIZE`
  - Reject:    drop   `release_gate/{project_id}.REJECT`

The gate polls every `config.TIER_B_POLL_INTERVAL_SEC` seconds and
times out after `config.TIER_B_TIMEOUT_HOURS` hours (default 72h).
"""

from __future__ import annotations

import logging
import time
from datetime import datetime, timezone
from typing import Any

from genesis import config
from genesis.state_db import update_task_status, log_event

log = logging.getLogger("governance.tier_b")


def _release_card(manifest: dict[str, Any], project_dir: str) -> str:
    """Generate a human-readable Markdown release card."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    goals_md = "\n".join(f"  - {g}" for g in manifest.get("goals", []))
    criteria_md = "\n".join(f"  - {c}" for c in manifest.get("test_criteria", []))

    return f"""\
# 🚀 Genesis Release Gate — Tier B Authorization Required

**Project:** `{manifest['name']}`
**Project ID:** `{manifest['project_id']}`
**Category:** {manifest.get('category')} → {manifest.get('subcategory')}
**Generated:** {now}

---

## Summary

{manifest.get('description', 'No description.')}

## Goals

{goals_md}

## Test Criteria (All Passed ✅)

{criteria_md}

## Project Location

`{project_dir}`

---

## Authorization Instructions

To **authorize** this release, create the file:
```
release_gate/{manifest['project_id']}.AUTHORIZE
```

To **reject and purge** this release, create the file:
```
release_gate/{manifest['project_id']}.REJECT
```

> ⚠️  This gate will auto-expire in {config.TIER_B_TIMEOUT_HOURS:.0f} hours if no action is taken.
> Expiration marks the project as `TIMEOUT` — no purge occurs automatically.

---

*Generated by Project Genesis — Autonomous Software Foundry*
"""


class TierBGate:
    """
    Issues a release card and blocks execution until Operator responds
    or the timeout is reached.
    """

    def freeze_and_notify(self, manifest: dict[str, Any]) -> str:
        """
        Write the release card and poll for Operator response.
        Returns: "AUTHORIZED" | "REJECTED" | "TIMEOUT"
        """
        project_id = manifest["project_id"]
        project_name = manifest["name"]
        project_dir = str(config.PROJECTS_DIR / project_name)

        # Write the release card
        card_path = config.RELEASE_GATE_DIR / f"{project_id}.PENDING.md"
        auth_path = config.RELEASE_GATE_DIR / f"{project_id}.AUTHORIZE"
        reject_path = config.RELEASE_GATE_DIR / f"{project_id}.REJECT"

        card_path.write_text(_release_card(manifest, project_dir), encoding="utf-8")
        log.info(f"[TierB] 🔒 Release card written: {card_path.name}")
        log_event(
            f"Tier B gate opened: {project_name}",
            category="GOVERNANCE",
            payload={"project_id": project_id, "card": str(card_path)},
        )
        update_task_status(project_id, "PENDING_RELEASE")

        # Poll loop
        timeout_sec = config.TIER_B_TIMEOUT_HOURS * 3600
        elapsed = 0.0
        poll = config.TIER_B_POLL_INTERVAL_SEC

        while elapsed < timeout_sec:
            if auth_path.exists():
                return self._handle_authorize(manifest, card_path, auth_path)
            if reject_path.exists():
                return self._handle_reject(manifest, card_path, reject_path)
            time.sleep(poll)
            elapsed += poll

        # Timeout
        log.warning(f"[TierB] ⏰ Timeout after {config.TIER_B_TIMEOUT_HOURS}h — {project_name}")
        update_task_status(project_id, "TIMEOUT")
        log_event(f"Tier B timeout: {project_name}", level="WARN",
                  category="GOVERNANCE", payload={"project_id": project_id})
        return "TIMEOUT"

    def _handle_authorize(
        self, manifest: dict[str, Any], card_path, auth_path
    ) -> str:
        project_id = manifest["project_id"]
        project_name = manifest["name"]
        log.info(f"[TierB] ✅ AUTHORIZED: {project_name}")

        # Record Tier B approval in feedback store
        from foundry.feedback_store import record_feedback
        record_feedback(
            project_name=project_name,
            category=manifest.get("category", "general"),
            tier="TIER_B",
            status="PASS",
            project_id=project_id,
        )

        # Tag the release in Git
        try:
            from vault.git_manager import GitManager
            gm = GitManager()
            version = datetime.now(timezone.utc).strftime("%Y%m%d.%H%M")
            gm.tag_release(project_name, version,
                           message=f"Operator-authorized release of {project_name}")
        except Exception as exc:
            log.warning(f"[TierB] Git tag failed: {exc}")

        update_task_status(project_id, "RELEASED")
        log_event(f"Tier B authorized: {project_name}", category="GOVERNANCE",
                  payload={"project_id": project_id})

        # Cleanup
        for p in [card_path, auth_path]:
            try:
                p.unlink(missing_ok=True)
            except Exception:
                pass

        return "AUTHORIZED"

    def _handle_reject(
        self, manifest: dict[str, Any], card_path, reject_path
    ) -> str:
        project_id = manifest["project_id"]
        project_name = manifest["name"]
        log.warning(f"[TierB] ❌ REJECTED & PURGED: {project_name}")

        # Read optional reject reason from reject file
        reason = "Operator manual rejection"
        try:
            content = reject_path.read_text(encoding="utf-8").strip()
            if content:
                reason = content
        except Exception:
            pass

        # Record Tier B rejection in feedback store
        from foundry.feedback_store import record_feedback
        record_feedback(
            project_name=project_name,
            category=manifest.get("category", "general"),
            tier="TIER_B",
            status="FAIL",
            project_id=project_id,
            failure_type="OPERATOR_REJECT",
            error_summary=reason,
        )

        # Purge the project directory
        import shutil
        project_dir = config.PROJECTS_DIR / project_name
        if project_dir.exists():
            shutil.rmtree(project_dir, ignore_errors=True)
            log.info(f"[TierB] Purged: {project_dir}")

        update_task_status(project_id, "REJECTED")
        log_event(f"Tier B rejected: {project_name}", level="WARN",
                  category="GOVERNANCE", payload={"project_id": project_id})

        for p in [card_path, reject_path]:
            try:
                p.unlink(missing_ok=True)
            except Exception:
                pass

        return "REJECTED"
