import os
import sys
import json
import time

if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
if sys.stderr and hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

def export_openapi_spec(tool_slug: str = None):
    os.makedirs("public/specs", exist_ok=True)
    
    if not tool_slug:
        # Fallback to active venture from pulse or telemetry
        pulse_file = "public/live_earnings_pulse.json"
        telemetry_file = "public/live_telemetry.json"
        if os.path.exists(pulse_file):
            try:
                with open(pulse_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    tool_slug = data.get("latest_venture")
            except Exception:
                pass
        if not tool_slug and os.path.exists(telemetry_file):
            try:
                with open(telemetry_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    tool_slug = data.get("active_venture")
            except Exception:
                pass
        if not tool_slug:
            tool_slug = f"service_{int(time.time())}"

    # Clean slug
    clean_slug = "".join([c if c.isalnum() else "_" for c in tool_slug]).strip("_")
    
    spec = {
        "openapi": "3.0.0",
        "info": {
            "title": f"Genesis API: {clean_slug}",
            "version": "1.0.0",
            "description": "Autonomous high-utility micro-endpoint generated by Project Genesis Swarm."
        },
        "paths": {
            "/execute": {
                "post": {
                    "summary": "Run payload analysis",
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {"data": {"type": "string"}}
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "description": "Successful execution response",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {"status": {"type": "string"}, "result": {"type": "string"}}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    out_file = f"public/specs/{clean_slug}_openapi.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(spec, f, indent=2)
        
    print(f"📦 OpenAPI Schema Generated: {out_file}")
    return out_file

if __name__ == "__main__":
    slug_arg = sys.argv[1] if len(sys.argv) > 1 else None
    export_openapi_spec(slug_arg)
