"""
vault/git_manager.py
====================
Central Artifact Vault — Git repository manager.

All validated projects are stored in a single Git-backed vault repo
at `config.PROJECTS_DIR`. Each project lives in its own sub-directory
and is tagged with a semantic version on release.

Git for Windows must be installed and on PATH.
Set GIT_PYTHON_GIT_EXECUTABLE env var if git is not auto-detected.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path

# Set executable path before importing git (Windows safety)
_git_exe = os.environ.get(
    "GIT_PYTHON_GIT_EXECUTABLE",
    r"C:\Program Files\Git\bin\git.exe",
)
if Path(_git_exe).exists():
    os.environ["GIT_PYTHON_GIT_EXECUTABLE"] = _git_exe

os.environ.setdefault("GIT_PYTHON_REFRESH", "quiet")

from git import Repo, Actor, InvalidGitRepositoryError   # noqa: E402

from genesis import config

log = logging.getLogger("vault.git")

_BOT_AUTHOR = Actor("Genesis Foundry Bot", "bot@genesis.local")


class GitManager:
    """
    Manages the Git repository at `config.PROJECTS_DIR`.
    Auto-initialises the repo if it doesn't exist.
    """

    def __init__(self) -> None:
        self.repo_path = config.PROJECTS_DIR
        self.repo = self._open_or_init()

    def _open_or_init(self) -> Repo:
        """Open an existing repo or initialise a new one."""
        try:
            repo = Repo(str(self.repo_path), search_parent_directories=False)
            log.debug(f"Opened existing vault repo at {self.repo_path}")
            return repo
        except InvalidGitRepositoryError:
            log.info(f"Initialising new vault Git repo at {self.repo_path}")
            repo = Repo.init(str(self.repo_path))
            # Create an initial commit so HEAD exists
            gitignore = self.repo_path / ".gitignore"
            gitignore.write_text("__pycache__/\n*.pyc\n.env\n", encoding="utf-8")
            repo.index.add([".gitignore"])
            repo.index.commit(
                "chore: init vault repository",
                author=_BOT_AUTHOR,
                committer=_BOT_AUTHOR,
            )
            return repo

    # -----------------------------------------------------------------------
    # Core operations
    # -----------------------------------------------------------------------

    def commit_project(self, project_id: str, project_name: str) -> str:
        """
        Stage all changes in the project sub-directory and commit them.
        Returns the short commit hash.
        """
        project_dir = self.repo_path / project_name
        if not project_dir.exists():
            log.warning(f"Project directory not found: {project_dir}")
            return ""

        # Add all files under the project subdirectory
        rel_path = str(project_dir.relative_to(self.repo_path))
        self.repo.git.add(rel_path)

        if not self.repo.is_dirty(index=True):
            log.info(f"[Git] Nothing to commit for '{project_name}'.")
            return ""

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        message = f"feat({project_name}): auto-generated by Genesis FOUNDRY [{timestamp}]"

        commit = self.repo.index.commit(
            message,
            author=_BOT_AUTHOR,
            committer=_BOT_AUTHOR,
        )
        short_sha = commit.hexsha[:8]
        log.info(f"[Git] Committed '{project_name}': {short_sha}")
        return short_sha

    def tag_release(self, project_name: str, version: str, message: str = "") -> None:
        """
        Create an annotated tag for a Tier B release.
        Tag name: `{project_name}/v{version}`
        """
        tag_name = f"{project_name}/v{version}"
        msg = message or f"Release {tag_name} by Genesis Operator"
        try:
            self.repo.create_tag(tag_name, message=msg)
            log.info(f"[Git] Tagged release: {tag_name}")
        except Exception as exc:
            log.warning(f"[Git] Tag creation failed: {exc}")

    def create_branch(self, branch_name: str, checkout: bool = False) -> None:
        """Create a new branch. Optionally check it out."""
        branch = self.repo.create_head(branch_name)
        if checkout:
            branch.checkout()
        log.info(f"[Git] Branch created: {branch_name}")

    def get_log(self, project_name: str | None = None, n: int = 10) -> list[dict]:
        """Return the last n commits, optionally filtered by project path."""
        commits = []
        kwargs: dict = {"max_count": n}
        if project_name:
            kwargs["paths"] = [project_name]
        for c in self.repo.iter_commits("HEAD", **kwargs):
            commits.append({
                "sha":     c.hexsha[:8],
                "message": c.summary,
                "author":  str(c.author),
                "date":    c.committed_datetime.isoformat(),
            })
        return commits
